stages:
    - test
    - full
    - image


test_job:
    stage: test
    image: registry.gitlab.com/gluttton/munkres-cpp
    before_script:
        - git checkout devel
        - BUILD_DIR=`pwd`/build
        - mkdir -p ${BUILD_DIR}
        - cd ${BUILD_DIR}
        - cmake -DCMAKE_BUILD_TYPE=Debug -DMUNKRESCPP_DEVEL_MODE=ON ${BUILD_DIR}/..
    script:
        - make tests
        - cd ${BUILD_DIR}/tests && ./munkrestest
        - cd ${BUILD_DIR}
        - make coverage
        - gcovr --exclude 'tests' --exclude 'build' -r ..
    only:
        - devel


full_job:
    stage: full
    image: registry.gitlab.com/gluttton/munkres-cpp
    before_script:
        - git checkout devel
        - BUILD_DIR=`pwd`/build
        - mkdir -p ${BUILD_DIR}
        - cd ${BUILD_DIR}
        - cmake -DCMAKE_BUILD_TYPE=Debug -DMUNKRESCPP_DEVEL_MODE=ON ${BUILD_DIR}/..
    script:
        - make examples
        - make benchmarks
        - make cppcheck
        - cat cppcheck.report
    only:
        - devel


image_job:
    stage: image
    image: docker:latest
    variables:
        DOCKER_DRIVER: overlay
    services:
        - docker:dind
    before_script:
        - docker info
    script:
        - docker login -u gitlab-ci-token -p $CI_JOB_TOKEN registry.gitlab.com
        - docker build -t registry.gitlab.com/gluttton/munkres-cpp .
        - docker push registry.gitlab.com/gluttton/munkres-cpp
    only:
        - docker
