stages:
    - build
    - test
    - full


build_job:
    stage: build
    image: gluttton/munkres-cpp:base
    before_script:
        - git checkout devel
        - BUILD_DIR=`pwd`/build
        - mkdir -p ${BUILD_DIR}
        - cd ${BUILD_DIR}
        - cmake -DCMAKE_BUILD_TYPE=Debug ${BUILD_DIR}/..
    script:
        - cd ${BUILD_DIR}
        - make


test_job:
    stage: test
    image: gluttton/munkres-cpp:complete
    before_script:
        - git checkout devel
        - BUILD_DIR=`pwd`/build
        - mkdir -p ${BUILD_DIR}
        - cd ${BUILD_DIR}
        - cmake -DCMAKE_BUILD_TYPE=Debug -DMUNKRESCPP_DEVEL_MODE=ON ${BUILD_DIR}/..
    script:
        - make tests
        - cd ${BUILD_DIR}/tests && ./munkrestest > /dev/null
        - cd ${BUILD_DIR}
        - mkdir coverage
        - cp -v ../src/*.h coverage
        - mv tests/CMakeFiles/munkrestest.dir/*.gcda coverage
        - mv tests/CMakeFiles/munkrestest.dir/*.gcno coverage
        - cd coverage
        - find . -type f -name '*.gcda' -exec gcov {} +
        - bash <(curl -s https://codecov.io/bash) -t 5a25c8bf-2d43-48cb-a813-9eef7f694194


full_job:
    stage: full
    image: gluttton/munkres-cpp:base
    before_script:
        - git checkout devel
        - BUILD_DIR=`pwd`/build
        - mkdir -p ${BUILD_DIR}
        - cd ${BUILD_DIR}
        - cmake -DCMAKE_BUILD_TYPE=Debug -DMUNKRESCPP_DEVEL_MODE=ON ${BUILD_DIR}/..
    script:
        - make example
        - make benchmarks
