stages:
    - image


image_job:
    stage: image
    image: docker:latest
    variables:
        DOCKER_DRIVER: overlay
    services:
        - docker:dind
    before_script:
        - docker info
    script:
        - docker login -u gitlab-ci-token -p $CI_JOB_TOKEN registry.gitlab.com
        - docker build -t registry.gitlab.com/gluttton/munkres-cpp .
        - docker push registry.gitlab.com/gluttton/munkres-cpp
    only:
        - docker
